### PR TITLE
Add python scripts for the creation of an idealised met file

### PR DESCRIPTION
**Pull request by Calebsakhtar**
This PR contains python scripts to produce idealised met files containing trapezoidal moist layers (in an altitude vs RHi plot).

***Trapezoid Moist Layer Parametrisation***
The trapezoid is symmetrical about its centre, and is parametrised as follows:
	- centre_altitude_m: The centre altitude in meters.
	- moist_depth_m: The moist layer depth in meters; the vertical extent of the moist layer.
	- RHi_background_PC: The background RHi in %, which is also the lowest RHi value in the trapezium.
	- RHi_peak_PC: The peak trapezium RHi in %. If too shallow a gradient is used, this value might not be reached.
	- grad_RHi_PC_per_m: The gradient of the trapezium sides in RHi % / vertical m. If too shallow a gradient is used,							the moist layer will be a triangle instead of a trapezium and its peak will be lower than or equal to the RHi_peak_PC value.

image

***Met File Parametrisation***
The met generator has additional parameters:
	- alt_resolution_m: The vertical interval (in m) at which the met is sampled at.
	- upper_alt_m: The vertical upper limit (in m) for met sampling.
	- shear: The horizontal wind shear (in 1/s). Constant throughout the entire met domain.
	- T_offset_K: A temperature offset (in K) from the ISA temperature distribution. Constant throughout the entire met
					domain.

Other than the RHi and shear, all other weather parameters assume the use of the International Standard Atmosphere. The temperature is decoupled from the pressure by assuming a constant alpha regardless of any temperature offset. The ideal gas relation is then used to calculate the air density from pressure and temperature to guarantee consistency.

***Required Python Modules***
The python version used to develop this code is python 3.9.15, with the following modules:
	- matplotlib 3.6.2
	- netcdf4 1.6.3
	- numpy 1.23.5
	- xarray 2023.12.0

***Deficiencies***
No distinction is made between dry and moist air density in this code. The difference is very small at altitude, but it is still a deficiency that needs to be addressed.

***Contact***
Please contact ca525@cam.ac.uk (or @Calebsakhtar on GitHub) for any queries or suggestions.

### CODE REVIEW

**Comment by Calebsakhtar** [comment]
@sdeastham Ask and you shall receive! Would you mind reviewing this PR?

**Comment by sdeastham** [comment]
Thanks @Calebsakhtar ! I just gave it a try - it looks mostly good, but the shear appears to be zero regardless of inputs (specifically, I inspected the output example met file with `ncump -v shear example-met.nc` and the shear values are all zeros. Can you check this please and update the PR? Thanks!

**Comment by Calebsakhtar** [comment]
@sdeastham Thanks for bringing this to my attention! Commit https://github.com/MIT-LAE/APCEMM/pull/33/commits/95d0d3c669ca6ca2e1158f8e24c82ba2f44bba32 just pushed to fix this issue. This bug is an artifact of my "cleanup" in which I renamed variables for code readability and ended up overriting the shear variable every time. Should be fixed now!

**Comment by sdeastham** [comment]
Great! Updated version looks good - at minimum this will give people something to start playing with. At some point in the future we should split this into a separate repo and possibly have it as a subrepo of this, but that can wait.

**Pull request merged**
